"""Exceptions raised by the harness.

EdTestError
 +-- EdPyCompatibilityError  the program uses something EdPy (or the robot) doesn't support; found before running
 +-- EdPyRuntimeError        while running, the program did something whose result on the robot is undefined or an error
 |                           (16-bit overflow, division by zero, list index out of range, ...)
 +-- UnsupportedInMock       the program calls an Ed function the mock doesn't model (never generated by the Lab)
 +-- StepLimitExceeded       a function called with Session.call() didn't return within its step or time budget

A whole-program run that hits its time or step budget isn't an error: robot programs often run forever. Program.run()
reports that as RunResult.status instead.
"""


class EdTestError(Exception):
    """Base class.

    kind          a machine-readable category: 'overflow', 'division_by_zero', 'index_out_of_range', 'type_error',
                  'negative_value', 'recursion', 'step_limit', 'python_error', 'unsupported', 'edpy_incompatible', ...
    line          the line in the EdPy program, when known; source_line is its text
    positions     (lineno, end_lineno, col_offset, end_col_offset) of the program frames when the error happened,
                  outermost first (col offsets in UTF-8 bytes, like CPython's); used to attribute the error to a block
    """

    def __init__(self, message, line=None, source_line=None, kind=None):
        super().__init__(message)
        self.message = message
        self.line = line
        self.source_line = source_line
        self.kind = kind
        self.positions = []

    def __str__(self):
        if self.line is None:
            return self.message
        where = 'line %d' % self.line
        if self.source_line:
            where += ': ' + self.source_line.strip()
        return '%s (%s)' % (self.message, where)


class EdPyCompatibilityError(EdTestError):
    pass


class EdPyRuntimeError(EdTestError):
    pass


class UnsupportedInMock(EdTestError):
    pass


class StepLimitExceeded(EdTestError):
    pass


class StopProgram(BaseException):
    """Internal: unwinds the program when a budget is exhausted. A BaseException, so program code can't swallow it."""

    def __init__(self, reason):
        super().__init__(reason)
        self.reason = reason
